Repository kubernetes-client/python-base, pull requests merged in 2019-09, with the labels that each got.

#160 Add property returncode to WSClient
  stream/ws_client.py
Labels: approved, cncf-cla: yes, lgtm, size/S

#158 Check is not None in safe_get
  config/kube_config.py
Labels: approved, cncf-cla: yes, lgtm, size/S

#157 Update ws_client.py to support proxy
  stream/ws_client.py
Labels: approved, cncf-cla: yes, lgtm, size/XS

#164 Use explicit API version for retrieving CRD API
  dynamic/test_client.py
Labels: approved, cncf-cla: yes, lgtm, size/XS

#161 Support false values in configuration file
  config/kube_config.py
  config/kube_config_test.py
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#163 Merging configs with missing fields
  config/kube_config.py
  config/kube_config_test.py
Labels: approved, cncf-cla: yes, lgtm, size/XS
