Repository kubernetes-client/python-base, pull requests merged in 2019-01, with the labels that each got.

#111 Use yaml.safe_load and yaml.safe_dump
  config/kube_config.py
  config/kube_config_test.py
Labels: approved, cncf-cla: yes, lgtm, size/S

#108 Make dependancy adal optional
  config/kube_config.py
Labels: approved, cncf-cla: yes, lgtm, size/XS

#109 fix watching with a specified resource version
  watch/watch.py
  watch/watch_test.py
Labels: approved, cncf-cla: yes, lgtm, size/M
