Repository kubernetes-client/python-base, pull requests merged in 2019-07, with the labels that each got.

#127 Drop Python3.4
  .travis.yml
  tox.ini
Labels: approved, cncf-cla: yes, lgtm, lifecycle/stale, size/XS

#141 Fix issue 84: Update _load_azure_token to hande str and int
  config/kube_config.py
  config/kube_config_test.py
Labels: approved, cncf-cla: yes, lgtm, size/L

#145 Generate docs in python3
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#146 Automated cherry pick of #79
  config/kube_config.py
  config/kube_config_test.py
Labels: approved, cncf-cla: yes, lgtm, size/L

#148 Remove sudo for Travis CI
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#147 Automated cherry pick of #79
  .travis.yml
  config/kube_config.py
  config/kube_config_test.py
  run_tox.sh
  tox.ini
Labels: approved, cncf-cla: yes, lgtm, size/L
