Repository kubernetes-client/python-base, pull requests merged in 2020-07, with the labels that each got.

#133 Retry expired watches
  watch/watch.py
  watch/watch_test.py
Labels: approved, cncf-cla: yes, lgtm, size/M

#202 Add old api_key to set auth attributes
  config/kube_config_test.py
Labels: approved, cncf-cla: yes, lgtm, size/XS

#204 Fix a Python 2 compatibility issue
  watch/watch.py
Labels: approved, cncf-cla: yes, lgtm, size/S

#201 FileOrData: Handle None object
  config/kube_config.py
  config/kube_config_test.py
Labels: approved, cncf-cla: yes, lgtm, size/S

#205 Accept client certificates from an authn/authz plugin
  config/kube_config.py
  config/kube_config_test.py
Labels: approved, cncf-cla: yes, lgtm, size/M
