Repository kubernetes-client/python-base, pull requests merged in 2020-09, with the labels that each got.

#210 Implement port forwarding.
  stream/__init__.py
  stream/stream.py
  stream/ws_client.py
Labels: approved, cncf-cla: yes, lgtm, size/L

#208 Support file-ish objects in config loading
  config/kube_config.py
  config/kube_config_test.py
Labels: approved, cncf-cla: yes, lgtm, size/M

#187 Prevent 503s from killing the client during discovery
  dynamic/discovery.py
Labels: approved, cncf-cla: yes, lgtm, size/S
