Repository kubernetes-client/python-base, pull requests merged in 2020-02, with the labels that each got.

#152 Refs. #151 -- detect binary payloads and send the correct opcode
  stream/ws_client.py
Labels: approved, cncf-cla: yes, lgtm, size/S

#169 config: Fix persist_config flag and function calls
  config/kube_config.py
  config/kube_config_test.py
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S

#171 Fixed Watch.unmarshal_event when data is not a JSON-serialized object
  watch/watch.py
Labels: approved, cncf-cla: yes, lgtm, size/XS

#184 Fix apiserver_id 'get' method
  config/kube_config.py
  config/kube_config_test.py
Labels: approved, cncf-cla: yes, lgtm, size/M
