Repository kubernetes-client/python-base, pull requests merged in 2021-05, with the labels that each got.

#237 rename method _websocket_reqeust to _websocket_request
  stream/stream.py
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#236 Support customizing “Accept” header #1428
  dynamic/client.py
  dynamic/test_client.py
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/M

#238 drop python2 support
  .travis.yml
  tox.ini
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/S
