Repository kubernetes-client/python-base, pull requests merged in 2021-10, with the labels that each got.

#257 fix typo in proxy auth (stream/ws_client.py)
  stream/ws_client.py
Labels: kind/bug, cncf-cla: yes, lgtm, size/XS, approved, release-note-none

#253 fix: ignore NotFoundError in the first call of LazyDiscoverer. __search
  dynamic/discovery.py
Labels: kind/bug, cncf-cla: yes, lgtm, size/XS, approved, release-note

#258 closes open file descriptors to prevent leaks
  config/kube_config.py
Labels: cncf-cla: yes, lgtm, size/XS, approved, release-note-none, needs-kind
