Repository kubernetes-client/python-base, pull requests merged in 2021-08, with the labels that each got.

#243 Add watch_stop to DynamicClient
  dynamic/client.py
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note-none, size/S

#247 Add support for dryRun parameter
  dynamic/client.py
Labels: kind/feature, cncf-cla: yes, lgtm, size/XS, approved, release-note

#244 Fix replication controller pods delete in tests
  dynamic/test_client.py
Labels: kind/bug, size/S, cncf-cla: yes, lgtm, approved, release-note-none
