Repository kubernetes-client/python-base, pull requests merged in 2021-11, with the labels that each got.

#262 Make socket Windows-proof
  stream/ws_client.py
Labels: kind/bug, cncf-cla: yes, lgtm, size/XS, approved, release-note-none

#266 [config] Add a new method of config.kube_config.new_client_from_config_dict
  config/__init__.py
  config/kube_config.py
  config/kube_config_test.py
Labels: size/S, cncf-cla: yes, lgtm, approved, release-note-none, needs-kind

#250 Refresh exec-based API credentials when they expire
  config/kube_config.py
  config/kube_config_test.py
Labels: kind/bug, cncf-cla: yes, lgtm, size/L, approved, release-note

#267 Fix leaderelection/example.py, now works in package.
  leaderelection/example.py
  leaderelection/resourcelock/configmaplock.py
Labels: kind/bug, cncf-cla: yes, lgtm, size/XS, approved, release-note-none
